# Generated by Django 3.1.7 on 2021-03-09 05:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='서적명')),
                ('publisher', models.CharField(blank=True, max_length=255, verbose_name='출판사')),
                ('page', models.IntegerField(blank=True, default=0, verbose_name='페이지 수')),
            ],
            options={
                'db_table': 'book',
            },
        ),
        migrations.CreateModel(
            name='Impression',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(blank=True, verbose_name='서평')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='impressions', to='cms.book', verbose_name='서적')),
            ],
            options={
                'db_table': 'impression',
            },
        ),
    ]
